baseURL: ''
languageCode: en-us
title: Akiru
theme: PaperMod
paginate: 5
enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true
minify:
  disableXML: true
languages:
  en:
    languageName: English
    weight: 1
    taxonomies:
      category: categories
      tag: tags
      series: series
    menu:
      main:
        - name: Archive
          url: archives
          weight: 5
        - name: Search
          url: search/
          weight: 10
        - name: Tags
          url: tags/
          weight: 10
        - name: WiKi
          url: 'https://github.com/adityatelange/hugo-PaperMod/wiki/'
        - name: Discord
          url: 'https://discord.gg/ahpmTvhVmp'
  fr:
    languageName: French
    languageAltTitle: French
    weight: 2
    title: PaperModL2
    taxonomies:
      category: FRcategories
      tag: FRtags
      series: FRseries
    profileMode:
      enabled: true
      title: PaperMod
      imageUrl: >-
        https://raw.githubusercontent.com/twitter/twemoji/master/assets/svg/1f317.svg
      imageTitle: ProfileMode image
      subtitle: "☄️ Fast | ☁️ Fluent | \U0001F319 Smooth | \U0001F4F1 Responsive"
      buttons:
        - name: Blog
          url: posts
        - name: Profile Mode
          url: >-
            https://github.com/adityatelange/hugo-PaperMod/wiki/Features#profile-mode
    menu:
      main:
        - name: Archive
          url: archives/
          weight: 5
        - name: FRTags
          url: frtags
          weight: 10
        - name: FRCategories
          url: frcategories
          weight: 10
        - name: FRSeries
          url: frseries
          weight: 10
        - name: NullLink
          url: '#'
  ar:
    languagedirection: rtl
    languageName: عربي
    weight: 3
    title: Akiru RTL
    homeInfoParams:
      Title: "مرحبا \U0001F44B"
      Content: Welcome to RTL layout
    taxonomies:
      category: FAcategories
      tag: FAtags
      series: FAseries
    menu:
      main:
        - name: وسوم
          url: fatags
          weight: 10
outputs:
  home:
    - HTML
    - RSS
    - JSON
params:
  env: production
  description: 'Theme PaperMod - https://github.com/adityatelange/hugo-PaperMod'
  author: Theme PaperMod
  defaultTheme: auto
  ShowShareButtons: true
  ShowReadingTime: true
  displayFullLangName: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowRssButtonInSectionTermList: true
  ShowToc: true
  images:
    - papermod-cover.png
  profileMode:
    enabled: false
    title: PaperMod
    imageUrl: '#'
    imageTitle: my image
    buttons:
      - name: Archives
        url: archives
      - name: Tags
        url: tags
  homeInfoParams:
    Title: PaperMod
    Content: "Welcome to demo of hugo's theme PaperMod.\n- **PaperMod** is a simple but fast and responsive theme with useful feature-set that enhances UX.\n- Do give a \U0001F31F on Github !\n- PaperMod is based on theme [Paper](https://github.com/nanxiaobei/hugo-paper).\n"
  socialIcons:
    - name: youtube
      url: 'https://youtube.com/@akiru'
    - name: instagram
      url: 'https://instagram.com/akirume'
    - name: Rss
      url: index.xml
  editPost:
    URL: 'https://github.com/adityatelange/hugo-PaperMod/tree/exampleSite/content'
    Text: Suggest Changes
    appendFilePath: true
  assets:
    disableHLJS: true
markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    noClasses: false
privacy:
  vimeo:
    disabled: false
    simple: true
  twitter:
    disabled: false
    enableDNT: true
    simple: true
  instagram:
    disabled: false
    simple: true
  youtube:
    disabled: false
    privacyEnhanced: true
services:
  instagram:
    disableInlineCSS: true
  twitter:
    disableInlineCSS: true
